logging.level:
  com.ddoong2.skeleton: debug
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
#  com.zaxxer: debug

## 설정을 주석처리하면 H2가 로드된다.
skeleton.datasource:
  write:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:dcrdb
    username: sa
    password:
  read:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:dcrdb
    username: sa
    password:

## 이걸 설정하면 자동설정이 로드되지 않는다
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:dcrdb
#    username: sa
#    password:
spring.jpa:
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      default_batch_fetch_size: 1000
      physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  generate-ddl: true
  hibernate:
    ddl-auto: create
